### ISSUE TITLE
Check to see if Erlang is installed

### ISSUE THREAD

**Issue by mlaccetti** [AlejandroRivera/embedded-rabbitmq#25]
Turns out I don't have Erlang installed on my workstation, so RabbitMQ doesn't kick on.  Boom thud goes the unit test.  It may be useful to see if the `erl` executable exists before anything else?  Perhaps also include that in the download/install?  (Scope creep, I know.)

**Comment by AlejandroRivera** [comment]
True, the unit test should have a check to see if the prerequisites are met. This should be easy enough to do (need to do some more research about how to detect it in Windows tho). 

Maybe the check could even happen prior to trying to download/extract/execute RabbitMQ in the prod. code; however, downloading/installing Erlang itself is something this library will never do.

If Erlang allowed for a self-contained binary distribution that didn't require to be installed, it might be doable, but i don't think that's the case as of now.

**Comment by AlejandroRivera** [comment]
PR #27 takes care of this improvement.
