### ISSUE TITLE
Download behind proxy

### ISSUE THREAD

**Issue by deathcoder** [AlejandroRivera/embedded-rabbitmq#35]
Hi, i'm trying to use embedded-rabbitmq behind a proxy, is it possible to configure the builder to work behind a proxy?

Thanks

**Comment by AlejandroRivera** [comment]
The code as it is doesn't have any settings you can enable to use a proxy. However, adding that functionality shouldn't be hard and I guess it would be a welcomed enhancement. Feel free to give it a try yourself and submit a Pull Request :)

**Comment by deathcoder** [comment]
#36 i created the pr :)

**Comment by AlejandroRivera** [comment]
PR #36 has been merged and new release has been generated: https://github.com/AlejandroRivera/embedded-rabbitmq/releases/tag/v1.2.1
