### ISSUE TITLE
Standard proxy property settings no longer respected

### ISSUE THREAD

**Issue by bitx1** [AlejandroRivera/embedded-rabbitmq#39]
I recently have upgraded to the latest release version (from 1.1.2) and I noticed I am no longer able to download artifacts behind my proxy. Upon some investigation, I noticed release 1.2.1 had made changes to "support" proxy -- which actually broke the standard way of setting proxy settings for Java applications.

Typically, you set your proxy settings in reserved system properties (i.e. http.proxyHost, http.proxyPort, http.nonProxyHosts, https.proxyHost, ....) and http-protocol handling classes look at these system properties to read (any applicable) proxy settings.

Prior to the library upgrade, I could download the rabbitmq artifacts through a proxy by setting the standard proxy system properties. With the latest version, I will now be forced to parse the system properties (if applicable) and configure the downloadProxy setting. As part of the parsing, I would also have to ensure the artifact repository domain is not part of the nonProxyHosts list.

Potential Resolution(s):
  1. revert the proxy commit change -- result: you can download thru the proxy using the standard proxy settings; this is a backward capability breaking change
  2. if you do not set downloadProxy (i.e. null), then it will resort to the default system implementation of handling http/https connections

**Comment by AlejandroRivera** [comment]
Thanks for the report, @bitx1. 
I've not had the "pleasure" of dealing with proxies, so I wasn't familiarized enough with the distinction of `Proxy.NO_PROXY` and leaving it "undefined" (ie. `null`).

I've started a new PR (#40) to make a backwards compatible fix using your second suggestion. I'll likely have this ready tomorrow after ironing out some wrinkles. Hope you don't mind the wait, but feel free to submit your own PR if you want :) Gotta get some sleep now.

**Comment by AlejandroRivera** [comment]
@bitx1, if you're able to, please try out release `1.2.3-SNAPSHOT` available in the Sonatype Snapshots Nexus repo.

@deathcoder, please try it out yourself as well since you requested this functionality.

https://oss.sonatype.org/content/repositories/snapshots/io/arivera/oss/embedded-rabbitmq/1.2.3-SNAPSHOT/

If all is good, I'll release shortly

**Comment by bitx1** [comment]
@AlejandroRivera  I have tested out your snapshot against multiple scenarios; namely combinations of (1) no settings, system proxy property settings, & manual downloadProxy settings (2) behind a firewall with a proxy & direct internet access

It looks good on my side!  BIG thanks for the VERY QUICK turnaround :)

**Comment by AlejandroRivera** [comment]
@bitx1, thanks for testing.

I've created the release
https://github.com/AlejandroRivera/embedded-rabbitmq/releases/tag/v1.2.3

**Comment by deathcoder** [comment]
Hi @AlejandroRivera, i probably won't have time to test the changes till next week, but i looked at the code change and it seems good to me, i honestly was not aware that leaving null was better than setting Proxy.NO_PROXY. 

i also want to thank you for bringing this to my attention, i deal with systems behind a proxy quite often and this is nice to know.
