### ISSUE TITLE
Error Parsing Erlang Version

### ISSUE THREAD

**Issue by redkhalil** [AlejandroRivera/embedded-rabbitmq#66]
![image](https://user-images.githubusercontent.com/16011713/107813758-d24c8f00-6dab-11eb-8beb-26b931805755.png)

The returned value using Erlang is shown below, perhaps the result has changed with newer Erlang version

![image](https://user-images.githubusercontent.com/16011713/107813807-dbd5f700-6dab-11eb-839a-0ddd5ce9168b.png)

Also might be good to surround the third commands (get version, halt) with single quotes.

**Comment by AlejandroRivera** [comment]
Fixed with new release [v1.5.0](https://github.com/AlejandroRivera/embedded-rabbitmq/releases/tag/v1.5.0) of this project
