### ISSUE TITLE
Delay for shutting down RMQ should be configurable

### ISSUE THREAD

**Issue by redkhalil** [AlejandroRivera/embedded-rabbitmq#71]
[warn] - io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.Process.rabbitmq-server - Gracefully halting Erlang VM
[info] mq.impl.RmqCluster2ImplSpec *** ABORTED ***
[info]   io.arivera.oss.embedded.rabbitmq.helpers.ShutDownException: Error while waiting 2000 MILLISECONDSfor RabbitMQ Server to shut down
[info]   at io.arivera.oss.embedded.rabbitmq.helpers.ShutdownHelper.confirmShutdown(ShutdownHelper.java:74)
[info]   at io.arivera.oss.embedded.rabbitmq.helpers.ShutdownHelper.run(ShutdownHelper.java:41)
[info]   at io.arivera.oss.embedded.rabbitmq.EmbeddedRabbitMq.stop(EmbeddedRabbitMq.java:91)
[info]   at mq.EmbeddedRabbitMq2Service.afterAll(EmbeddedRabbitMq2Service.scala:19)
[info]   at mq.impl.RmqCluster2ImplSpec.test$OneActorSystemPerTest$$super$afterAll(RmqCluster2ImplSpec.scala:15)
[info]   at test.OneActorSystemPerTest.afterAll(OneActorSystemPerTest.scala:25)
[info]   at test.OneActorSystemPerTest.afterAll$(OneActorSystemPerTest.scala:22)
[info]   at mq.impl.RmqCluster2ImplSpec.afterAll(RmqCluster2ImplSpec.scala:15)
[info]   at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:379)
[info]   ...
[info]   Cause: java.util.concurrent.TimeoutException:
[info]   at java.util.concurrent.FutureTask.get(FutureTask.java:205)

**Comment by AlejandroRivera** [comment]
Try looking at https://github.com/AlejandroRivera/embedded-rabbitmq/blob/2d2014fdc7f5b58ebc76f02d97f43df6ec037e8d/src/main/java/io/arivera/oss/embedded/rabbitmq/helpers/ShutdownHelper.java#L34

If that works for you please close this bug, if not, please elaborate
